# Generated by Django 2.1 on 2019-06-28 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'article')},
        ),
    ]
